(() => {
  const root=window.TitanWorkCore=window.TitanWorkCore||{};
  const state={online:navigator.onLine,reachable:null,quality:'unknown',effectiveType:navigator.connection?.effectiveType||'unknown',saveData:Boolean(navigator.connection?.saveData),latency:null,lastChecked:null,wifiOnlyLargeUploads:false,largeTransferBytes:5*1024*1024,reducedPayload:false};
  let previousReachable=null;
  const emit=()=>window.dispatchEvent(new CustomEvent('workcore:network-changed',{detail:{...state}}));
  function classify(){const c=navigator.connection;state.online=navigator.onLine;state.effectiveType=c?.effectiveType||'unknown';state.saveData=Boolean(c?.saveData);if(!state.online||state.reachable===false)state.quality='offline';else if(state.saveData||['slow-2g','2g'].includes(state.effectiveType)||(state.latency&&state.latency>1800))state.quality='weak';else if(state.effectiveType==='3g'||(state.latency&&state.latency>700))state.quality='unstable';else state.quality='good';state.reducedPayload=state.quality==='weak'||state.quality==='unstable'||state.saveData;}
  async function checkReachability({timeout=5000}={}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout),started=performance.now();try{let response=await fetch(root.contracts.endpoints.reachability,{method:'HEAD',credentials:'same-origin',cache:'no-store',signal:controller.signal});if(response.status===405)response=await fetch(root.contracts.endpoints.reachability,{method:'GET',credentials:'same-origin',cache:'no-store',signal:controller.signal,headers:{Accept:'application/json'}});state.reachable=response.ok;state.latency=Math.round(performance.now()-started);}catch(_){state.reachable=false;state.latency=null;}finally{clearTimeout(timer);state.lastChecked=new Date().toISOString();classify();emit();if(state.reachable&&previousReachable===false)window.dispatchEvent(new CustomEvent('workcore:network-restored',{detail:{...state}}));previousReachable=state.reachable;}return state.reachable;}
  function shouldPauseLargeTransfer(bytes=0){if(bytes<state.largeTransferBytes)return false;if(state.quality==='offline'||state.quality==='weak')return true;if(state.wifiOnlyLargeUploads&&navigator.connection?.type&&navigator.connection.type!=='wifi')return true;return false;}
  function waitForTransferPermission(bytes=0,{signal=null}={}){if(!shouldPauseLargeTransfer(bytes))return Promise.resolve();return new Promise((resolve,reject)=>{const abort=()=>{cleanup();reject(new DOMException('Transfer cancelled.','AbortError'));};const changed=()=>{if(!shouldPauseLargeTransfer(bytes)){cleanup();resolve();}};const cleanup=()=>{window.removeEventListener('workcore:network-changed',changed);signal?.removeEventListener('abort',abort)};window.addEventListener('workcore:network-changed',changed);signal?.addEventListener('abort',abort,{once:true});if(signal?.aborted)abort();});}
  function requestHeaders(headers={}){return {...headers,...(state.reducedPayload?{'X-Reduced-Payload':'1','Save-Data':'on'}:{})};}
  function setPreferences(prefs={}){if(typeof prefs.wifiOnlyLargeUploads==='boolean')state.wifiOnlyLargeUploads=prefs.wifiOnlyLargeUploads;if(Number.isFinite(prefs.largeTransferBytes))state.largeTransferBytes=prefs.largeTransferBytes;localStorage.setItem('titan-workcore-network',JSON.stringify({wifiOnlyLargeUploads:state.wifiOnlyLargeUploads,largeTransferBytes:state.largeTransferBytes}));classify();emit();}
  try{setPreferences(JSON.parse(localStorage.getItem('titan-workcore-network')||'{}'))}catch(_){}
  window.addEventListener('online',()=>{state.online=true;checkReachability();});window.addEventListener('offline',()=>{previousReachable=state.reachable;state.online=false;state.reachable=false;classify();emit();});navigator.connection?.addEventListener?.('change',()=>{classify();emit();});
  classify();root.network={state,checkReachability,shouldPauseLargeTransfer,waitForTransferPermission,requestHeaders,setPreferences};
})();
