<?php

$searchEmailSchema = [
    'type' => 'object',
    'properties' => [
        'query' => ['type' => 'string', 'description' => 'Provider search query.'],
        'max_results' => ['type' => 'integer', 'minimum' => 1, 'maximum' => 20],
    ],
    'required' => ['query'],
];

$messageIdSchema = static fn (string $field): array => [
    'type' => 'object',
    'properties' => [$field => ['type' => 'string']],
    'required' => [$field],
];

return [
    'version' => '1.9.0',
    'tenancy' => [
        'user_company_columns' => ['company_id', 'team_id'],
        'user_role_columns' => ['company_role', 'team_role'],
        'manager_roles' => ['owner', 'admin', 'manager'],
    ],
    'imports' => [
        'max_upload_kilobytes' => 5120,
        'max_archive_entries' => 250,
        'max_uncompressed_bytes' => 25 * 1024 * 1024,
        'max_file_bytes' => 2 * 1024 * 1024,
        'max_instruction_bytes' => 1024 * 1024,
        'max_github_tree_bytes' => 5 * 1024 * 1024,
        'max_compression_ratio' => 100.0,
        'max_directory_depth' => 5,
        'staging_ttl_minutes' => 60,
        'allowed_resource_directories' => ['scripts', 'references', 'assets'],
        'allowed_extensions' => [
            'scripts' => ['js', 'mjs', 'cjs', 'ts', 'py', 'sh', 'sql'],
            'references' => ['md', 'markdown', 'txt', 'json', 'yaml', 'yml', 'csv', 'xml', 'html', 'htm', 'pdf'],
            'assets' => ['png', 'jpg', 'jpeg', 'gif', 'webp', 'svg', 'ico', 'css', 'json', 'txt'],
        ],
        'github_hosts' => ['github.com'],
        'http_timeout_seconds' => 15,
    ],
    'tools' => [
        'catalog' => [
            [
                'key' => 'core.generate_image',
                'function_name' => 'generate_image',
                'description' => 'Generate an image from a text prompt.',
                'source' => 'core',
                'input_schema' => [
                    'type' => 'object',
                    'properties' => ['prompt' => ['type' => 'string']],
                    'required' => ['prompt'],
                ],
                'capabilities' => ['image.generate'],
                'approval' => 'never',
            ],
            [
                'key' => 'core.search_images',
                'function_name' => 'search_images',
                'description' => 'Search for existing images.',
                'source' => 'core',
                'input_schema' => [
                    'type' => 'object',
                    'properties' => ['query' => ['type' => 'string']],
                    'required' => ['query'],
                ],
                'capabilities' => ['image.search'],
                'approval' => 'never',
            ],
            [
                'key' => 'connector.gmail.search_emails',
                'function_name' => 'connector_gmail_search_emails',
                'description' => 'Search connected Gmail messages.',
                'source' => 'connector',
                'input_schema' => $searchEmailSchema,
                'capabilities' => ['email.search'],
                'approval' => 'never',
            ],
            [
                'key' => 'connector.gmail.get_email',
                'function_name' => 'connector_gmail_get_email',
                'description' => 'Read a connected Gmail message.',
                'source' => 'connector',
                'input_schema' => $messageIdSchema('message_id'),
                'capabilities' => ['email.read'],
                'approval' => 'never',
            ],
            [
                'key' => 'connector.outlook.search_emails',
                'function_name' => 'connector_outlook_search_emails',
                'description' => 'Search connected Outlook messages.',
                'source' => 'connector',
                'input_schema' => $searchEmailSchema,
                'capabilities' => ['email.search'],
                'approval' => 'never',
            ],
            [
                'key' => 'connector.outlook.get_email',
                'function_name' => 'connector_outlook_get_email',
                'description' => 'Read a connected Outlook message.',
                'source' => 'connector',
                'input_schema' => $messageIdSchema('message_id'),
                'capabilities' => ['email.read'],
                'approval' => 'never',
            ],
            [
                'key' => 'connector.google-drive.search_files',
                'function_name' => 'connector_google_drive_search_files',
                'description' => 'Search connected Google Drive files.',
                'source' => 'connector',
                'input_schema' => [
                    'type' => 'object',
                    'properties' => [
                        'query' => ['type' => 'string'],
                        'max_results' => ['type' => 'integer', 'minimum' => 1, 'maximum' => 20],
                        'mime_type' => ['type' => 'string'],
                    ],
                    'required' => ['query'],
                ],
                'capabilities' => ['drive.search'],
                'approval' => 'never',
            ],
            [
                'key' => 'connector.google-drive.get_file_content',
                'function_name' => 'connector_google_drive_get_file_content',
                'description' => 'Read supported text content from Google Drive.',
                'source' => 'connector',
                'input_schema' => $messageIdSchema('file_id'),
                'capabilities' => ['drive.read'],
                'approval' => 'never',
            ],
            [
                'key' => 'connector.google-calendar.list_upcoming_events',
                'function_name' => 'connector_google_calendar_list_upcoming_events',
                'description' => 'List upcoming connected Google Calendar events.',
                'source' => 'connector',
                'input_schema' => [
                    'type' => 'object',
                    'properties' => [
                        'max_results' => ['type' => 'integer', 'minimum' => 1, 'maximum' => 20],
                        'time_horizon_days' => ['type' => 'integer', 'minimum' => 1, 'maximum' => 90],
                    ],
                    'required' => [],
                ],
                'capabilities' => ['calendar.read'],
                'approval' => 'never',
            ],
            [
                'key' => 'connector.google-calendar.find_events',
                'function_name' => 'connector_google_calendar_find_events',
                'description' => 'Find connected Google Calendar events.',
                'source' => 'connector',
                'input_schema' => [
                    'type' => 'object',
                    'properties' => [
                        'query' => ['type' => 'string'],
                        'max_results' => ['type' => 'integer', 'minimum' => 1, 'maximum' => 20],
                    ],
                    'required' => ['query'],
                ],
                'capabilities' => ['calendar.read'],
                'approval' => 'never',
            ],
            [
                'key' => 'connector.notion.search_pages',
                'function_name' => 'connector_notion_search_pages',
                'description' => 'Search connected Notion pages and databases.',
                'source' => 'connector',
                'input_schema' => $searchEmailSchema,
                'capabilities' => ['notion.search'],
                'approval' => 'never',
            ],
            [
                'key' => 'connector.notion.get_page',
                'function_name' => 'connector_notion_get_page',
                'description' => 'Read a connected Notion page.',
                'source' => 'connector',
                'input_schema' => $messageIdSchema('page_id'),
                'capabilities' => ['notion.read'],
                'approval' => 'never',
            ],
            [
                'key' => 'ai-agent.ai-call',
                'function_name' => 'ai_agent_ai_call',
                'description' => 'Delegate an AI reasoning action to the AI Agent runtime.',
                'source' => 'ai-agent',
                'capabilities' => ['ai-agent.execute'],
                'approval' => 'conditional',
            ],
            [
                'key' => 'ai-agent.generate-report',
                'function_name' => 'ai_agent_generate_report',
                'description' => 'Generate a durable report through the AI Agent runtime.',
                'source' => 'ai-agent',
                'capabilities' => ['report.generate'],
                'approval' => 'conditional',
            ],
            [
                'key' => 'ai-agent.send-message',
                'function_name' => 'ai_agent_send_message',
                'description' => 'Send an external message through the governed AI Agent runtime.',
                'source' => 'ai-agent',
                'capabilities' => ['communication.send'],
                'approval' => 'required',
            ],
            [
                'key' => 'ai-agent.workflow',
                'function_name' => 'ai_agent_workflow',
                'description' => 'Start or resume a durable AI Agent workflow.',
                'source' => 'ai-agent',
                'capabilities' => ['workflow.execute'],
                'approval' => 'conditional',
            ],
        ],
    ],
];
