(() => {
  const root=window.TitanWorkCore=window.TitanWorkCore||{}; const DB=()=>root.db,S=()=>root.contracts.stores,now=()=>new Date().toISOString();
  const normalise=v=>String(v||'').toLowerCase().normalize('NFKD').replace(/[^a-z0-9\s]/g,' ');
  async function cacheMedia(articleId, media=[]){ for(const item of media){ const id=String(item.id||item.uuid||item.url); if(!id||!item.url)continue; const existing=await DB().get(S().knowledgeMedia,id); if(existing?.version===item.version&&existing?.blob)continue; const response=await fetch(item.url,{credentials:'same-origin'}); if(!response.ok)throw new Error(`Knowledge media download failed (${response.status})`); const blob=await response.blob(); await DB().put(S().knowledgeMedia,{id,article_id:String(articleId),url:item.url,type:blob.type,size:blob.size,checksum:item.checksum||null,version:item.version||1,blob,cached_at:now(),updated_at:item.updated_at||now()}); } }
  async function removeArticle(id){ const key=String(id), media=await DB().byIndex(S().knowledgeMedia,'by_article',key); for(const item of media)await DB().remove(S().knowledgeMedia,item.id); await DB().remove(S().knowledgeArticles,key); }
  async function upsert(article){ const key=String(article.id||article.uuid),existing=await DB().get(S().knowledgeArticles,key); const row={id:key,title:article.title||'',content:article.content||'',summary:article.summary||'',category_id:article.category_id||null,role_key:article.role_key||null,relationships:article.relationships||[],media:article.media||[],version:Number(article.version||1),is_favourite:article.is_favourite===undefined?Boolean(existing?.is_favourite):Boolean(article.is_favourite),is_emergency:Boolean(article.is_emergency),revoked:Boolean(article.revoked),obsolete:Boolean(article.obsolete),updated_at:article.updated_at||now(),cached_at:now(),search_text:normalise([article.title,article.summary,article.content].join(' '))}; await DB().put(S().knowledgeArticles,row); if(article.cache_media!==false&&row.media.length)await cacheMedia(row.id,row.media); return row; }
  async function download({articleIds=[],categoryIds=[],roleKey=null,cursor=null,signal=null}={}){ const url=new URL(root.contracts.endpoints.knowledge,location.origin); articleIds.forEach(id=>url.searchParams.append('article_ids[]',id)); categoryIds.forEach(id=>url.searchParams.append('category_ids[]',id)); if(roleKey)url.searchParams.set('role',roleKey); if(cursor)url.searchParams.set('cursor',cursor); const response=await fetch(url,{credentials:'same-origin',signal,headers:root.network?.requestHeaders({Accept:'application/json'})||{Accept:'application/json'}}); if(!response.ok)throw new Error(`Knowledge download failed (${response.status})`); const payload=await response.json(); for(const article of payload.articles||payload.data||[])await upsert(article); for(const id of payload.revoked_ids||[])await removeArticle(id); await DB().setMeta('knowledge_cursor',payload.next_cursor??null); await DB().setMeta('knowledge_last_refresh',now()); window.dispatchEvent(new CustomEvent('workcore:knowledge-updated',{detail:{count:(payload.articles||payload.data||[]).length}})); return payload; }
  async function refresh(options={}){ const cursor=await DB().getMeta('knowledge_cursor'); return download({cursor,...options}); }
  async function downloadAll(options={}){ let cursor=options.cursor||null,pages=0,total=0,last=null; const seenCursors=new Set(); do{ if(cursor&&seenCursors.has(cursor))throw new Error('Knowledge cursor cycle detected.'); if(cursor)seenCursors.add(cursor); last=await download({...options,cursor}); pages++; total+=(last.articles||last.data||[]).length; cursor=last.next_cursor??null; if(pages>=Number(options.maxPages||100)&&cursor&&last.has_more!==false)throw new Error('Knowledge download exceeded the configured page limit.'); }while(cursor&&last.has_more!==false); return {pages,total,next_cursor:cursor,last}; }
  async function search(query,{categoryId=null,roleKey=null,limit=50}={}){ const terms=normalise(query).split(/\s+/).filter(Boolean),rows=await DB().all(S().knowledgeArticles); return rows.filter(r=>!r.revoked&&!r.obsolete&&(!categoryId||String(r.category_id)===String(categoryId))&&(!roleKey||!r.role_key||r.role_key===roleKey)).map(r=>({...r,score:terms.reduce((score,t)=>score+((r.search_text||'').includes(t)?1:0),0)})).filter(r=>!terms.length||r.score>0).sort((a,b)=>Number(b.is_emergency)-Number(a.is_emergency)||b.score-a.score||new Date(b.updated_at)-new Date(a.updated_at)).slice(0,limit); }
  async function favourite(id,value=true){ const row=await DB().get(S().knowledgeArticles,String(id)); if(!row)return null; row.is_favourite=value; row.updated_at=now(); await DB().put(S().knowledgeArticles,row); return row; }
  async function stale({maxAgeDays=14}={}){ const cutoff=Date.now()-maxAgeDays*86400000; return (await DB().all(S().knowledgeArticles)).filter(r=>!r.is_emergency&&new Date(r.cached_at||r.updated_at).getTime()<cutoff); }
  let reconnectRefreshRunning=false;window.addEventListener('workcore:network-restored',async()=>{if(reconnectRefreshRunning)return;reconnectRefreshRunning=true;try{await refresh({maxPages:10});}catch(error){window.dispatchEvent(new CustomEvent('workcore:knowledge-refresh-failed',{detail:{error:error.message}}));}finally{reconnectRefreshRunning=false;}});root.knowledge={upsert,download,downloadAll,refresh,search,favourite,stale,cacheMedia,removeArticle,all:()=>DB().all(S().knowledgeArticles),media:()=>DB().all(S().knowledgeMedia)};
})();
