<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up(): void {
Schema::create('titan_ai_governed_memories',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->unsignedBigInteger('tenant_id')->index();$t->unsignedBigInteger('user_id')->nullable()->index();$t->string('scope',32);$t->string('subject_type')->nullable();$t->string('subject_id')->nullable();$t->json('payload');$t->unsignedTinyInteger('importance')->default(1);$t->string('status',24)->default('active');$t->boolean('authoritative')->default(false);$t->unsignedInteger('reinforcement_count')->default(0);$t->unsignedBigInteger('approved_by')->nullable();$t->timestamp('approved_at')->nullable();$t->timestamp('last_reinforced_at')->nullable();$t->timestamp('expires_at')->nullable()->index();$t->json('metadata')->nullable();$t->timestamps();});
Schema::create('titan_ai_persona_assignments',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->unsignedBigInteger('tenant_id')->index();$t->unsignedBigInteger('user_id')->nullable()->index();$t->string('context_type');$t->string('context_id')->nullable();$t->string('name');$t->json('definition');$t->boolean('active')->default(true);$t->unsignedBigInteger('assigned_by');$t->timestamps();});
Schema::create('titan_ai_governed_skills',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->unsignedBigInteger('tenant_id')->index();$t->string('slug');$t->string('name');$t->json('definition');$t->boolean('active')->default(true);$t->unsignedBigInteger('updated_by');$t->timestamps();$t->unique(['tenant_id','slug']);});
Schema::create('titan_ai_tool_permissions',function(Blueprint $t){$t->id();$t->unsignedBigInteger('tenant_id')->index();$t->string('subject_type');$t->string('subject_id');$t->string('tool_name');$t->boolean('allowed')->default(false);$t->json('constraints')->nullable();$t->unsignedBigInteger('updated_by');$t->timestamps();$t->unique(['tenant_id','subject_type','subject_id','tool_name'],'titan_ai_tool_permission_unique');});
Schema::create('titan_ai_skill_evaluations',function(Blueprint $t){$t->id();$t->unsignedBigInteger('tenant_id')->index();$t->unsignedBigInteger('skill_id')->index();$t->string('execution_id')->index();$t->boolean('passed');$t->json('metrics');$t->timestamp('evaluated_at');$t->timestamps();}); }
public function down(): void { foreach(['titan_ai_skill_evaluations','titan_ai_tool_permissions','titan_ai_governed_skills','titan_ai_persona_assignments','titan_ai_governed_memories'] as $table) Schema::dropIfExists($table); } };
