<?php

declare(strict_types=1);

return [
    'provider_adapters' => [
        'openai-image' => ['status' => 'adapter-required', 'capabilities' => ['image.generate','image.edit']],
        'fal-ai' => ['status' => 'adapter-required', 'capabilities' => ['image.generate','video.generate']],
        'freepik' => ['status' => 'adapter-required', 'capabilities' => ['image.generate','image.edit']],
        'clipdrop' => ['status' => 'adapter-required', 'capabilities' => ['image.edit','background.remove']],
        'novita' => ['status' => 'adapter-required', 'capabilities' => ['image.generate']],
        'together' => ['status' => 'adapter-required', 'capabilities' => ['image.realtime']],
        'gamma' => ['status' => 'adapter-required', 'capabilities' => ['presentation.generate']],
        'pebblely' => ['status' => 'adapter-required', 'capabilities' => ['product-shot.generate']],
        'midjourney-piapi' => ['status' => 'adapter-required', 'capabilities' => ['image.generate']],
        'google-lyria' => ['status' => 'adapter-required', 'capabilities' => ['music.generate']],
        'elevenlabs-dubbing' => ['status' => 'adapter-required', 'capabilities' => ['video.dub','audio.generate']],
        'heygen' => ['status' => 'adapter-required', 'capabilities' => ['video.generate','video.dub']],
        'ffmpeg' => ['status' => 'local-adapter-required', 'capabilities' => ['video.edit','video.export']],
        'serper' => ['status' => 'adapter-required', 'capabilities' => ['seo.search']],
        'wordpress' => ['status' => 'connector-required', 'capabilities' => ['blog.publish']],
        'mailchimp' => ['status' => 'connector-required', 'capabilities' => ['newsletter.publish']],
        'meta' => ['status' => 'connector-required', 'capabilities' => ['facebook.publish','instagram.publish']],
        'linkedin' => ['status' => 'connector-required', 'capabilities' => ['linkedin.publish']],
        'x' => ['status' => 'connector-required', 'capabilities' => ['x.publish']],
        'tiktok' => ['status' => 'connector-required', 'capabilities' => ['tiktok.publish']],
        'telegram' => ['status' => 'connector-required', 'capabilities' => ['telegram.publish']],
        'whatsapp' => ['status' => 'connector-required', 'capabilities' => ['whatsapp.campaign']],
    ],
    'generation_job_types' => [
        'manual','ai_image','realtime_image','image_edit','product_shot','photoshoot','fashion_try_on','presentation',
        'ai_video','video_to_video','url_to_video','viral_clip','video_dubbing','video_export','ai_music','annotation_edit',
    ],
    'publication_channel_types' => ['internal','blog','newsletter','facebook','instagram','linkedin','x','tiktok','telegram','whatsapp'],
    'donor_classification' => [
        'advanced-image' => ['decision' => 'integrated_concept', 'accepted_concepts' => ['multi-provider image job','image edit workflow'], 'rejected_authorities' => ['provider settings','webhook routes','credit deductions']],
        'ai-image-pro' => ['decision' => 'integrated_concept', 'accepted_concepts' => ['durable image generation','gallery metadata','generation polling'], 'rejected_authorities' => ['user image tables','login middleware','provider client']],
        'ai-photoshoot' => ['decision' => 'integrated_concept', 'accepted_concepts' => ['photoshoot projects','background replacement','asset creation'], 'rejected_authorities' => ['duplicate products','provider settings','public media paths']],
        'ai-presentation' => ['decision' => 'integrated_concept', 'accepted_concepts' => ['presentation generation job','presentation asset'], 'rejected_authorities' => ['credit ownership','Gamma provider client','free-item billing']],
        'ai-product-shot' => ['decision' => 'integrated_concept', 'accepted_concepts' => ['product-shot generation type'], 'rejected_authorities' => ['settings columns','provider key storage','user-owned Pebblely table']],
        'ai-realtime-image' => ['decision' => 'integrated_concept', 'accepted_concepts' => ['realtime generation lifecycle'], 'rejected_authorities' => ['Together provider client','global settings','demo authority']],
        'creative-suite' => ['decision' => 'integrated_concept', 'accepted_concepts' => ['creative projects','private assets','revisions'], 'rejected_authorities' => ['duplicate documents','editor routes','global settings']],
        'creative-suite-ai-template' => ['decision' => 'integrated_concept', 'accepted_concepts' => ['versioned content templates'], 'rejected_authorities' => ['provider execution','editor injection']],
        'creative-suite-annotations' => ['decision' => 'integrated_concept', 'accepted_concepts' => ['annotation-driven revision'], 'rejected_authorities' => ['vision provider client','editor injection','settings authority']],
        'flux-pro' => ['decision' => 'deferred_provider', 'accepted_concepts' => ['image generation adapter definition'], 'rejected_authorities' => ['webhook controller','provider-specific UI tabs']],
        'midjourney' => ['decision' => 'deferred_provider', 'accepted_concepts' => ['image generation adapter definition'], 'rejected_authorities' => ['PiAPI client','webhook controller','provider settings']],
        'nano-banana' => ['decision' => 'deferred_provider', 'accepted_concepts' => ['image generation adapter definition'], 'rejected_authorities' => ['provider-specific UI tabs','webhook controller']],
        'see-dream-v4' => ['decision' => 'deferred_provider', 'accepted_concepts' => ['image generation adapter definition'], 'rejected_authorities' => ['provider-specific UI tabs','webhook controller']],
        'ai-video-pro' => ['decision' => 'integrated_concept', 'accepted_concepts' => ['video generation job','durable output'], 'rejected_authorities' => ['provider client','credit deductions','global settings']],
        'ai-video-to-video' => ['decision' => 'integrated_concept', 'accepted_concepts' => ['video-to-video job type'], 'rejected_authorities' => ['provider client','public upload routes']],
        'ai-viral-clips' => ['decision' => 'integrated_concept', 'accepted_concepts' => ['clip extraction project','generation outputs'], 'rejected_authorities' => ['provider client','duplicate media storage']],
        'url-to-video' => ['decision' => 'integrated_concept', 'accepted_concepts' => ['URL source metadata','video generation job'], 'rejected_authorities' => ['remote fetch controller','provider settings']],
        'video-dubbing' => ['decision' => 'integrated_concept', 'accepted_concepts' => ['dubbing job','language metadata'], 'rejected_authorities' => ['ElevenLabs client','Heygen client','download job']],
        'video-editor' => ['decision' => 'integrated_concept', 'accepted_concepts' => ['video project','asset revisions','export job'], 'rejected_authorities' => ['FFmpeg execution','duplicate project routes','public uploads']],
        'ai-music' => ['decision' => 'integrated_concept', 'accepted_concepts' => ['music generation job','audio asset'], 'rejected_authorities' => ['user music authority','provider client']],
        'ai-music-pro' => ['decision' => 'integrated_concept', 'accepted_concepts' => ['music provider metadata','lyrics parameter'], 'rejected_authorities' => ['Lyria client','credit ownership','settings authority']],
        'fashion-studio' => ['decision' => 'integrated_concept', 'accepted_concepts' => ['fashion project type','virtual try-on job','wardrobe asset metadata'], 'rejected_authorities' => ['duplicate product catalogue','provider settings','public media paths']],
        'ai-social-media' => ['decision' => 'integrated_concept', 'accepted_concepts' => ['content calendar','approval-aware social content'], 'rejected_authorities' => ['Instagram client','scheduler commands','global automation settings']],
        'blogpilot' => ['decision' => 'integrated_concept', 'accepted_concepts' => ['blog campaign','content approval','publication queue'], 'rejected_authorities' => ['duplicate post authority','provider execution','demo seeders']],
        'marketing-bot' => ['decision' => 'integrated_concept', 'accepted_concepts' => ['campaign plan','automation definition','channel publication'], 'rejected_authorities' => ['duplicate inbox','contact authority','WhatsApp and Telegram clients','embedding authority']],
        'newsletter' => ['decision' => 'integrated_concept', 'accepted_concepts' => ['newsletter draft'], 'rejected_authorities' => ['duplicate mailing list','provider send route']],
        'seo-tool' => ['decision' => 'integrated_concept', 'accepted_concepts' => ['SEO brief','source references'], 'rejected_authorities' => ['Serper client','unverified web search execution']],
        'social-media' => ['decision' => 'integrated_concept', 'accepted_concepts' => ['publication channels','publication lifecycle','analytics observations'], 'rejected_authorities' => ['OAuth ownership','platform clients','token refresh commands','duplicate posts']],
        'social-media-agent' => ['decision' => 'integrated_concept', 'accepted_concepts' => ['agent-assisted content planning','trend observation','performance advice metadata'], 'rejected_authorities' => ['duplicate chat','provider execution','demo seeders']],
        'social-media-automation' => ['decision' => 'integrated_concept', 'accepted_concepts' => ['automation definition','automation run ledger'], 'rejected_authorities' => ['public webhook execution','platform permission authority','direct publishing']],
    ],
];
