<?php

declare(strict_types=1);

return [
    'connectors' => [
        'gmail' => ['status' => 'adapter-required', 'scopes' => ['mail.read','mail.send']],
        'outlook' => ['status' => 'adapter-required', 'scopes' => ['mail.read','mail.send','calendar.read']],
        'google-drive' => ['status' => 'adapter-required', 'scopes' => ['files.read']],
        'google-calendar' => ['status' => 'adapter-required', 'scopes' => ['calendar.read','calendar.write']],
        'notion' => ['status' => 'adapter-required', 'scopes' => ['pages.read']],
        'slack' => ['status' => 'adapter-required', 'scopes' => ['messages.read','messages.send']],
        'whatsapp' => ['status' => 'adapter-required', 'scopes' => ['messages.send','webhooks.receive']],
        'telegram' => ['status' => 'adapter-required', 'scopes' => ['messages.send','webhooks.receive']],
        'messenger' => ['status' => 'adapter-required', 'scopes' => ['messages.send','webhooks.receive']],
        'instagram' => ['status' => 'adapter-required', 'scopes' => ['messages.send','webhooks.receive']],
        'hubspot' => ['status' => 'adapter-required', 'scopes' => ['crm.read','crm.write']],
        'mailchimp' => ['status' => 'adapter-required', 'scopes' => ['audience.read','campaign.send']],
        'xero' => ['status' => 'adapter-required', 'scopes' => ['accounting.read','accounting.write']],
        'wordpress' => ['status' => 'adapter-required', 'scopes' => ['content.read','content.write']],
        'cloudflare-r2' => ['status' => 'adapter-required', 'scopes' => ['objects.read','objects.write']],
    ],
    'providers' => [
        'openai' => ['status' => 'supported-by-host', 'capabilities' => ['chat','tools','vision','audio']],
        'azure-openai' => ['status' => 'adapter-required', 'capabilities' => ['chat','tools','vision']],
        'openrouter' => ['status' => 'adapter-required', 'capabilities' => ['chat','tools','model-routing']],
        'perplexity' => ['status' => 'adapter-required', 'capabilities' => ['chat','web-research']],
        'gemini' => ['status' => 'supported-by-host', 'capabilities' => ['chat','tools','vision']],
        'anthropic' => ['status' => 'adapter-required', 'capabilities' => ['chat','tools','vision']],
        'ollama' => ['status' => 'adapter-required', 'capabilities' => ['chat','local']],
    ],
    'voice_providers' => [
        'twilio' => ['status' => 'adapter-required', 'capabilities' => ['telephony']],
        'elevenlabs' => ['status' => 'adapter-required', 'capabilities' => ['tts','voice-agent']],
        'azure-tts' => ['status' => 'adapter-required', 'capabilities' => ['tts']],
        'openai-realtime' => ['status' => 'adapter-required', 'capabilities' => ['stt','tts','realtime']],
    ],
    'donor_classification' => [
        'ai-agent' => 'integrated-native-runtime',
        'ai-agent-gmail' => 'optional-agent-connector-adapter',
        'ai-agent-outlook' => 'optional-agent-connector-adapter',
        'ai-agent-slack-channel' => 'optional-agent-channel-adapter',
        'ai-agent-tool-chatbot' => 'integrated-channel-tool-concept',
        'ai-agent-tool-marketing-bot' => 'deferred-marketing-creative',
        'ai-agent-tool-social-media' => 'deferred-marketing-creative',
        'ai-agent-whatsapp-channel' => 'optional-agent-channel-adapter',
        'ai-avatar' => 'deferred-marketing-creative',
        'ai-captions' => 'deferred-marketing-creative',
        'ai-chat-pro' => 'integrated-native-runtime',
        'ai-chat-pro-deep-research' => 'integrated-session-concept',
        'ai-chat-pro-entity-highlight' => 'integrated-workspace-concept',
        'ai-chat-pro-file-chat' => 'integrated-document-context-concept',
        'ai-chat-pro-folders' => 'integrated-native-runtime',
        'ai-chat-pro-gmail' => 'optional-connector-adapter',
        'ai-chat-pro-google-calendar' => 'optional-connector-adapter',
        'ai-chat-pro-google-drive' => 'optional-connector-adapter',
        'ai-chat-pro-highlight-to-ask' => 'integrated-workspace-concept',
        'ai-chat-pro-memory' => 'integrated-native-runtime',
        'ai-chat-pro-notion' => 'optional-connector-adapter',
        'ai-chat-pro-outlook' => 'optional-connector-adapter',
        'ai-chat-pro-skills' => 'integrated-native-runtime',
        'ai-chat-pro-smart-image' => 'deferred-marketing-creative',
        'ai-persona' => 'deferred-marketing-creative',
        'ai-writer-templates' => 'deferred-marketing-creative',
        'announcement' => 'integrated-host-experience',
        'azure-openai' => 'optional-provider-adapter',
        'azure-tts' => 'optional-voice-adapter',
        'canvas' => 'integrated-native-runtime',
        'chat-pro-temp-chat' => 'integrated-native-runtime',
        'chat-setting' => 'quarantined-duplicate-settings',
        'chat-share' => 'integrated-native-runtime',
        'chatbot' => 'integrated-channel-concept',
        'chatbot-agent' => 'integrated-agent-channel-concept',
        'chatbot-booking' => 'rejected-duplicate-workcore',
        'chatbot-customer-tag' => 'rejected-duplicate-crm',
        'chatbot-ecommerce' => 'rejected-duplicate-commerce',
        'chatbot-instagram' => 'optional-channel-adapter',
        'chatbot-messenger' => 'optional-channel-adapter',
        'chatbot-review' => 'deferred-marketing-creative',
        'chatbot-telegram' => 'optional-channel-adapter',
        'chatbot-voice' => 'integrated-voice-concept',
        'chatbot-voice-call' => 'integrated-voice-concept',
        'chatbot-whatsapp' => 'optional-channel-adapter',
        'checkout-registration' => 'rejected-duplicate-auth-billing',
        'cloudflare-r2' => 'optional-storage-adapter',
        'content-manager' => 'quarantined-global-cms',
        'cryptomus' => 'rejected-unapproved-payment-provider',
        'discount-manager' => 'rejected-duplicate-finance',
        'elevenlabs-voice-chat' => 'optional-voice-adapter',
        'focus-mode' => 'integrated-workspace-concept',
        'hubspot' => 'optional-connector-adapter',
        'influencer-avatar' => 'deferred-marketing-creative',
        'introductions' => 'integrated-host-experience',
        'live-customizer' => 'quarantined-global-theme-authority',
        'mailchimp-newsletter' => 'optional-connector-adapter',
        'maintenance' => 'quarantined-public-maintenance-risk',
        'mega-menu' => 'quarantined-duplicate-interface',
        'menu' => 'quarantined-duplicate-interface',
        'migration' => 'quarantined-magicai-schema',
        'model-council' => 'integrated-provider-routing',
        'multi-model' => 'integrated-provider-routing',
        'onboarding-pro' => 'integrated-host-experience',
        'open-router' => 'optional-provider-adapter',
        'openai-realtime-chat' => 'optional-voice-adapter',
        'perplexity' => 'optional-provider-adapter',
        'phone-call-agent' => 'integrated-voice-concept',
        'plagiarism' => 'deferred-marketing-creative',
        'ugc-creator' => 'deferred-marketing-creative',
        'ugc-factory' => 'deferred-marketing-creative',
        'voice-isolator' => 'optional-voice-processing-adapter',
        'webchat' => 'integrated-channel-concept',
        'wordpress' => 'optional-connector-adapter',
        'xero' => 'optional-finance-connector-adapter',
    ],
];
