<?php

declare(strict_types=1);

use App\Domains\WorkCore\System\Outbox\NullOutboxTransport;

$module = static function (string $key, array $permissions, array $extra = []): array {
    return array_replace_recursive([
        'routes_enabled' => false,
        'route_prefix' => "api/workcore/{$key}",
        'middleware' => ['api', 'auth:sanctum', 'titan.company'],
        'permissions' => $permissions,
    ], $extra);
};

return [
    'version' => '0.4.0',
    'enabled' => env('WORKCORE_ENABLED', true),
    'require_tenant' => true,
    'identity' => [
        'user_model' => App\Models\User::class,
        'company_model' => App\Models\Company::class,
        'active_company_column' => 'active_company_id',
    ],
    'tenancy' => [
        'header' => env('TITAN_COMPANY_HEADER', 'X-Titan-Company'),
        'session_key' => env('TITAN_COMPANY_SESSION_KEY', 'titan_company_id'),
        'routes_enabled' => false,
    ],
    'context' => [
        'default_locale' => 'en_AU',
        'default_timezone' => 'Australia/Melbourne',
        'default_currency' => 'AUD',
        'default_country' => 'AU',
    ],
    'permissions' => ['allow_platform_fallback' => false],
    'outbox' => [
        'enabled' => true,
        'transport' => env('WORKCORE_OUTBOX_TRANSPORT', NullOutboxTransport::class),
        'max_attempts' => 10,
        'retry_seconds' => 60,
        'max_retry_seconds' => 3600,
        'processing_timeout_seconds' => 300,
        'consumers' => [],
    ],
    'capabilities' => [
        'workcore.core', 'workcore.crm', 'workcore.premises', 'workcore.catalogue',
        'workcore.operations', 'workcore.scheduling', 'workcore.dispatch', 'workcore.workforce',
        'workcore.rosters', 'workcore.assets', 'workcore.inventory', 'workcore.forms',
        'workcore.attendance', 'workcore.support', 'workcore.knowledge', 'workcore.reviews',
        'workcore.supply', 'workcore.fleet', 'workcore.repairs', 'workcore.trade_compliance',
        'workcore.documents', 'workcore.assurance', 'workcore.accommodation',
        'workcore.finance', 'workcore.payments', 'workcore.trust_accounting',
    ],
    'crm' => $module('crm', [
        'customers' => ['view' => 'workcore.crm.customers.view', 'create' => 'workcore.crm.customers.create'],
        'contacts' => ['create' => 'workcore.crm.contacts.create', 'update' => 'workcore.crm.contacts.update'],
        'leads' => [
            'view' => 'workcore.crm.leads.view', 'create' => 'workcore.crm.leads.create',
            'update' => 'workcore.crm.leads.update', 'convert' => 'workcore.crm.leads.convert',
        ],
    ]),
    'premises' => $module('premises', [
        'view' => 'workcore.premises.view', 'create' => 'workcore.premises.create',
        'approve' => 'workcore.premises.approve', 'archive' => 'workcore.premises.archive',
        'manage_spaces' => 'workcore.premises.spaces.manage',
        'manage_hazards' => 'workcore.premises.hazards.manage',
        'manage_access' => 'workcore.premises.access.manage',
        'manage_service_plans' => 'workcore.premises.service_plans.manage',
        'record_meter_readings' => 'workcore.premises.meter_readings.record',
        'manage_identifiers' => 'workcore.premises.identifiers.manage',
        'manage_contacts' => 'workcore.premises.contacts.manage',
        'manage_documents' => 'workcore.premises.documents.manage',
        'manage_party_roles' => 'workcore.premises.party_roles.manage',
        'manage_agreements' => 'workcore.premises.agreements.manage',
        'manage_occupancies' => 'workcore.premises.occupancies.manage',
    ]),
    'accommodation' => $module('accommodation', [
        'view' => 'workcore.accommodation.view',
        'manage_rates' => 'workcore.accommodation.rates.manage',
        'manage_reservations' => 'workcore.accommodation.reservations.manage',
        'check_in' => 'workcore.accommodation.check_in',
        'check_out' => 'workcore.accommodation.check_out',
        'housekeeping' => 'workcore.accommodation.housekeeping',
        'charges' => 'workcore.accommodation.charges',
    ]),
    'finance' => $module('finance', [
        'view' => 'workcore.finance.view',
        'create_quotes' => 'workcore.finance.quotes.create',
        'manage_quotes' => 'workcore.finance.quotes.manage',
        'create_invoices' => 'workcore.finance.invoices.create',
        'issue_invoices' => 'workcore.finance.invoices.issue',
        'manage_invoices' => 'workcore.finance.invoices.manage',
        'credit_notes' => 'workcore.finance.credit_notes.manage',
        'expenses' => 'workcore.finance.expenses.record',
        'approve_expenses' => 'workcore.finance.expenses.approve',
        'allocate_receivables' => 'workcore.finance.receivables.allocate',
        'manage_accounts' => 'workcore.finance.accounts.manage',
        'manage_periods' => 'workcore.finance.periods.manage',
        'post_journals' => 'workcore.finance.journals.post',
    ]),
    'payments' => $module('payments', [
        'view' => 'workcore.payments.view',
        'create_sessions' => 'workcore.payments.sessions.create',
        'record_attempts' => 'workcore.payments.attempts.record',
        'record_observations' => 'workcore.payments.observations.record',
        'match' => 'workcore.payments.matches.manage',
        'reconcile' => 'workcore.payments.reconcile',
    ]),
    'trust_accounting' => $module('trust_accounting', [
        'view' => 'workcore.trust_accounting.view',
        'manage_accounts' => 'workcore.trust_accounting.accounts.manage',
        'manage_matters' => 'workcore.trust_accounting.matters.manage',
        'record_receipts' => 'workcore.trust_accounting.receipts.record',
        'allocate_receipts' => 'workcore.trust_accounting.receipts.allocate',
        'request_disbursements' => 'workcore.trust_accounting.disbursements.request',
        'approve_disbursements' => 'workcore.trust_accounting.disbursements.approve',
        'release_disbursements' => 'workcore.trust_accounting.disbursements.release',
        'reverse_ledger' => 'workcore.trust_accounting.ledger.reverse',
    ]),
    'catalogue' => $module('catalogue', ['manage' => 'workcore.catalogue.manage']),
    'operations' => $module('operations', [
        'view' => 'workcore.operations.view', 'create' => 'workcore.operations.create',
        'status' => 'workcore.operations.status', 'tasks_update' => 'workcore.operations.tasks.update',
        'time_entries_create' => 'workcore.operations.time_entries.create',
    ]),
    'scheduling' => $module('scheduling', ['view' => 'workcore.scheduling.view', 'manage' => 'workcore.scheduling.manage']),
    'dispatch' => $module('dispatch', ['view' => 'workcore.dispatch.view', 'manage' => 'workcore.dispatch.manage']),
    'workforce' => $module('workforce', ['view' => 'workcore.workforce.view', 'manage' => 'workcore.workforce.manage']),
    'rosters' => $module('rosters', ['view' => 'workcore.rosters.view', 'manage' => 'workcore.rosters.manage']),
    'assets' => $module('assets', ['view' => 'workcore.assets.view', 'manage' => 'workcore.assets.manage']),
    'inventory' => $module('inventory', ['view' => 'workcore.inventory.view', 'manage' => 'workcore.inventory.manage']),
    'forms' => $module('forms', ['view' => 'workcore.forms.view', 'manage' => 'workcore.forms.manage']),
    'attendance' => $module('attendance', ['view' => 'workcore.attendance.view', 'manage' => 'workcore.attendance.manage']),
    'support' => $module('support', ['view' => 'workcore.support.view', 'manage' => 'workcore.support.manage']),
    'knowledge' => $module('knowledge', ['view' => 'workcore.knowledge.view', 'manage' => 'workcore.knowledge.manage']),
    'reviews' => $module('reviews', ['view' => 'workcore.reviews.view', 'manage' => 'workcore.reviews.manage']),
    'supply' => $module('supply', ['view' => 'workcore.supply.view', 'manage' => 'workcore.supply.manage']),
    'fleet' => $module('fleet', ['view' => 'workcore.fleet.view', 'manage' => 'workcore.fleet.manage']),
    'repairs' => $module('repairs', ['view' => 'workcore.repairs.view', 'manage' => 'workcore.repairs.manage']),
];
