import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
const root=path.resolve(import.meta.dirname,'../..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
test('Agent 4 stores share the WorkCore database contract',()=>{const c=read('resources/pwa/chatbot-pwa/workcore/contracts.js');for(const name of ['attachmentChunks','knowledgeArticles','knowledgeMedia','offlinePacks'])assert.match(c,new RegExp(name));assert.match(c,/version: 7/g);});
test('unsynchronised attachments are protected',()=>{const a=read('resources/pwa/chatbot-pwa/workcore/attachments.js');assert.match(a,/Unsynchronised attachments cannot be deleted/);assert.match(a,/protected_until_synced/);assert.match(a,/Content-Range/);assert.match(a,/X-Chunk-SHA256/);});
test('service worker excludes sensitive data and supports cache verification',()=>{const sw=read('resources/pwa/chatbot-sw.js');assert.match(sw,/SENSITIVE_PATHS/);assert.match(sw,/VERIFY_PWA_CACHE/);assert.match(sw,/previous static shell for rollback/);assert.doesNotMatch(sw,/cache\.put\([^\n]*\/api\//);});
test('knowledge, packs, storage and readiness modules are loaded',()=>{const view=read('resources/views/frontend-ui/components/pwa.blade.php');for(const file of ['network.js','knowledge.js','offline-packs.js','storage.js','readiness.js','resilience-ui.js'])assert.match(view,new RegExp(file.replace('.','\\.')));});
test('pass 2 validates file signatures and reconciles resumable sessions',()=>{const a=read('resources/pwa/chatbot-pwa/workcore/attachments.js');assert.match(a,/sniffMime/);assert.match(a,/File signature does not match declared MIME type/);assert.match(a,/reconcileSession/);assert.match(a,/cancelUpload/);});
test('pass 2 caches knowledge media and reports quota pressure',()=>{const k=read('resources/pwa/chatbot-pwa/workcore/knowledge.js');const s=read('resources/pwa/chatbot-pwa/workcore/storage.js');assert.match(k,/cacheMedia/);assert.match(k,/knowledgeMedia/);assert.match(k,/removeArticle/);assert.match(s,/pressure:/);assert.match(s,/ensureCapacity/);});
test('pass 2 advances shared database and shell contracts',()=>{const c=read('resources/pwa/chatbot-pwa/workcore/contracts.js');const sw=read('resources/pwa/chatbot-sw.js');assert.match(c,/version: 7/g);assert.match(c,/version: '2\.2\.0'/g);assert.match(sw,/v11-five-tier-ai-final/g);assert.match(sw,/X-Authenticated-User/);});

test('pass 3 fixes favourite mutation and supports paged knowledge downloads',()=>{const k=read('resources/pwa/chatbot-pwa/workcore/knowledge.js');assert.match(k,/async function favourite[\s\S]*return row; \}/);assert.doesNotMatch(k,/async function favourite[\s\S]{0,350}article\.cache_media/);assert.match(k,/downloadAll/);assert.match(k,/maxPages/);assert.match(k,/signal/);});
test('pass 3 protects shared offline-pack attachments',()=>{const p=read('resources/pwa/chatbot-pwa/workcore/offline-packs.js');const a=read('resources/pwa/chatbot-pwa/workcore/attachments.js');assert.match(p,/cancelRefresh/);assert.match(p,/estimateRequiredBytes/);assert.match(p,/pack_ids/);assert.match(p,/Insufficient device storage/);assert.match(a,/pack_ids/);});
test('pass 3 clears completed chunk state and advances runtime contracts',()=>{const a=read('resources/pwa/chatbot-pwa/workcore/attachments.js');const c=read('resources/pwa/chatbot-pwa/workcore/contracts.js');const sw=read('resources/pwa/chatbot-sw.js');assert.match(a,/byIndex\(S\(\)\.attachmentChunks,'by_attachment'/);assert.match(a,/DB\(\)\.remove\(S\(\)\.attachmentChunks/);assert.match(c,/version: 7/g);assert.match(c,/version: '2\.2\.0'/g);assert.match(sw,/v11-five-tier-ai-final/g);});

test('pass 4 rejects unverified strict file signatures and cleans attachment chunks',()=>{const a=read('resources/pwa/chatbot-pwa/workcore/attachments.js');assert.match(a,/Unable to verify file signature/);assert.match(a,/removeAttachmentChunks/);assert.doesNotMatch(a,/'image\/svg\+xml'/);});
test('pass 4 prevents stale and cyclic knowledge cursors',()=>{const k=read('resources/pwa/chatbot-pwa/workcore/knowledge.js');assert.match(k,/knowledge_cursor',payload\.next_cursor\?\?null/);assert.match(k,/seenCursors/);assert.match(k,/Knowledge cursor cycle detected/);assert.match(k,/existing\?\.is_favourite/);});
test('pass 4 makes database upgrades cooperative and transaction completion race safe',()=>{const d=read('resources/pwa/chatbot-pwa/workcore/database.js');assert.match(d,/const done = transactionDone\(tx\)/);assert.match(d,/onversionchange/);assert.match(d,/workcore:database-versionchange/);});
test('pass 4 limits navigation caching and supports reachability GET fallback',()=>{const sw=read('resources/pwa/chatbot-sw.js');const n=read('resources/pwa/chatbot-pwa/workcore/network.js');assert.doesNotMatch(sw,/safePut\(PAGE_CACHE, request, response/);assert.match(n,/method:'GET'/);assert.match(n,/response\.status===405/);});
