<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void
    {
        Schema::create('titanpay_gateway_connections',function(Blueprint $table):void{$table->ulid('id')->primary();$table->ulid('company_id')->index();$table->string('provider');$table->string('display_name');$table->string('vault_secret_reference')->nullable();$table->string('merchant_account_reference')->nullable();$table->string('environment')->default('sandbox');$table->json('configuration_json')->nullable();$table->bigInteger('minimum_amount_minor')->nullable();$table->bigInteger('maximum_amount_minor')->nullable();$table->char('currency_code',3)->default('AUD');$table->boolean('is_active')->default(true);$table->timestamps();$table->unique(['company_id','provider','merchant_account_reference']);$table->foreign('company_id')->references('id')->on('companies')->cascadeOnDelete();});
        Schema::create('titanpay_collection_sessions',function(Blueprint $table):void{$table->ulid('id')->primary();$table->ulid('company_id')->index();$table->ulid('invoice_id')->nullable();$table->string('receivable_type')->nullable();$table->string('receivable_id')->nullable();$table->ulid('gateway_connection_id')->nullable();$table->string('reference')->unique();$table->string('public_token_hash',64)->unique();$table->string('public_token_hint',10);$table->bigInteger('amount_minor');$table->char('currency_code',3);$table->json('allowed_methods_json');$table->string('selected_method')->nullable();$table->json('payer_context_json')->nullable();$table->text('return_url')->nullable();$table->string('status')->default('pending')->index();$table->string('gateway_reference')->nullable();$table->json('gateway_payload_json')->nullable();$table->timestamp('expires_at')->index();$table->timestamp('opened_at')->nullable();$table->timestamp('completed_at')->nullable();$table->timestamp('failed_at')->nullable();$table->text('failure_reason')->nullable();$table->foreignId('created_by_user_id')->nullable();$table->string('created_by_agent_id')->nullable();$table->string('conversation_id')->nullable();$table->ulid('correlation_id')->nullable();$table->timestamps();$table->foreign('company_id')->references('id')->on('companies')->cascadeOnDelete();$table->foreign('invoice_id')->references('id')->on('titan_money_invoices')->restrictOnDelete();$table->foreign('gateway_connection_id')->references('id')->on('titanpay_gateway_connections')->nullOnDelete();});
        Schema::create('titanpay_transactions',function(Blueprint $table):void{$table->ulid('id')->primary();$table->ulid('company_id')->index();$table->ulid('collection_session_id');$table->ulid('titan_money_payment_id')->nullable();$table->string('provider');$table->string('gateway_transaction_id');$table->string('idempotency_key')->unique();$table->string('type')->default('payment');$table->string('status')->index();$table->bigInteger('amount_minor');$table->bigInteger('fee_minor')->default(0);$table->char('currency_code',3);$table->string('reference')->nullable();$table->timestamp('verified_at')->nullable();$table->timestamp('settled_at')->nullable();$table->timestamp('refunded_at')->nullable();$table->json('metadata_json')->nullable();$table->timestamps();$table->unique(['provider','gateway_transaction_id']);$table->foreign('company_id')->references('id')->on('companies')->cascadeOnDelete();$table->foreign('collection_session_id')->references('id')->on('titanpay_collection_sessions')->cascadeOnDelete();$table->foreign('titan_money_payment_id')->references('id')->on('titan_money_payments')->nullOnDelete();});
        Schema::create('titanpay_payment_claims',function(Blueprint $table):void{$table->ulid('id')->primary();$table->ulid('company_id')->index();$table->ulid('collection_session_id');$table->string('method');$table->bigInteger('amount_minor');$table->char('currency_code',3);$table->string('reference')->nullable();$table->string('status')->default('submitted')->index();$table->string('payer_name')->nullable();$table->string('payer_email')->nullable();$table->text('notes')->nullable();$table->timestamp('submitted_at');$table->timestamp('reviewed_at')->nullable();$table->foreignId('reviewed_by_user_id')->nullable();$table->text('rejection_reason')->nullable();$table->json('metadata_json')->nullable();$table->timestamps();$table->foreign('company_id')->references('id')->on('companies')->cascadeOnDelete();$table->foreign('collection_session_id')->references('id')->on('titanpay_collection_sessions')->cascadeOnDelete();});
        Schema::create('titanpay_payment_evidence',function(Blueprint $table):void{$table->ulid('id')->primary();$table->ulid('company_id')->index();$table->ulid('payment_claim_id');$table->string('disk');$table->string('path');$table->string('original_name');$table->string('mime_type');$table->unsignedBigInteger('size_bytes');$table->string('sha256',64);$table->json('metadata_json')->nullable();$table->foreignId('created_by_user_id')->nullable();$table->timestamps();$table->foreign('company_id')->references('id')->on('companies')->cascadeOnDelete();$table->foreign('payment_claim_id')->references('id')->on('titanpay_payment_claims')->cascadeOnDelete();});
        Schema::create('titanpay_bank_accounts',function(Blueprint $table):void{$table->ulid('id')->primary();$table->ulid('company_id')->index();$table->string('display_name');$table->string('account_name')->nullable();$table->string('bsb_masked')->nullable();$table->string('account_number_masked')->nullable();$table->string('payid_type')->nullable();$table->string('payid_value_masked')->nullable();$table->string('vault_secret_reference')->nullable();$table->char('currency_code',3)->default('AUD');$table->boolean('is_default')->default(false);$table->boolean('is_active')->default(true);$table->json('metadata_json')->nullable();$table->timestamps();$table->foreign('company_id')->references('id')->on('companies')->cascadeOnDelete();});
        Schema::create('titanpay_bank_deposits',function(Blueprint $table):void{$table->ulid('id')->primary();$table->ulid('company_id')->index();$table->ulid('bank_account_id')->nullable();$table->string('external_id')->nullable();$table->date('transaction_date');$table->text('description')->nullable();$table->string('reference')->nullable();$table->bigInteger('amount_minor');$table->char('currency_code',3)->default('AUD');$table->string('status')->default('unmatched')->index();$table->ulid('matched_collection_session_id')->nullable();$table->ulid('matched_payment_id')->nullable();$table->json('metadata_json')->nullable();$table->timestamps();$table->unique(['company_id','external_id']);$table->foreign('company_id')->references('id')->on('companies')->cascadeOnDelete();});
        Schema::create('titanpay_gateway_events',function(Blueprint $table):void{$table->ulid('id')->primary();$table->ulid('company_id')->index();$table->string('provider');$table->string('event_id');$table->string('event_type');$table->string('merchant_account_reference')->nullable();$table->boolean('signature_valid');$table->string('payload_hash',64);$table->text('payload_encrypted');$table->timestamp('received_at');$table->timestamp('processed_at')->nullable();$table->string('processing_status')->index();$table->text('failure_reason')->nullable();$table->string('idempotency_key')->unique();$table->json('metadata_json')->nullable();$table->timestamps();$table->unique(['provider','event_id']);$table->foreign('company_id')->references('id')->on('companies')->cascadeOnDelete();});
        Schema::create('titanpay_gateway_logs',function(Blueprint $table):void{$table->ulid('id')->primary();$table->ulid('company_id')->index();$table->ulid('collection_session_id')->nullable();$table->string('provider');$table->string('direction');$table->string('operation');$table->string('status');$table->json('request_json')->nullable();$table->json('response_json')->nullable();$table->unsignedSmallInteger('http_status')->nullable();$table->unsignedInteger('duration_ms')->nullable();$table->text('error_message')->nullable();$table->timestamps();$table->foreign('company_id')->references('id')->on('companies')->cascadeOnDelete();});
        Schema::create('titanpay_qr_codes',function(Blueprint $table):void{$table->ulid('id')->primary();$table->ulid('collection_session_id');$table->text('payload');$table->string('format')->default('text');$table->timestamp('expires_at')->nullable();$table->json('metadata_json')->nullable();$table->timestamps();$table->foreign('collection_session_id')->references('id')->on('titanpay_collection_sessions')->cascadeOnDelete();});
    }
    public function down():void{foreach(['titanpay_qr_codes','titanpay_gateway_logs','titanpay_gateway_events','titanpay_bank_deposits','titanpay_bank_accounts','titanpay_payment_evidence','titanpay_payment_claims','titanpay_transactions','titanpay_collection_sessions','titanpay_gateway_connections'] as $table)Schema::dropIfExists($table);}
};
