{{-- Unified offline-first PWA bootstrap. --}}
<link rel="manifest" href="{{ asset('chatbot.webmanifest') }}">
<link rel="apple-touch-icon" sizes="180x180" href="{{ asset('chatbot-pwa/icons/apple-touch-icon.png') }}">
<link rel="stylesheet" href="{{ asset('chatbot-pwa/pwa.css') }}">
<link rel="stylesheet" href="{{ asset('vendor/chatbot/css/titan-generative-ui.css') }}">
<meta name="theme-color" content="#111318"><meta name="mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"><meta name="apple-mobile-web-app-title" content="Titan Chat"><meta name="application-name" content="Titan Zero Chatbot"><meta name="format-detection" content="telephone=no">
<meta name="workcore-api-base" content="{{ config('chatbot.workcore_api_base', '') }}"><meta name="workcore-company-id" content="{{ auth()->user()?->active_company_id ?? '' }}"><meta name="workcore-user-id" content="{{ auth()->id() ?? '' }}"><meta name="csrf-token" content="{{ csrf_token() }}">
<div class="chatbot-pwa-status" data-kind="offline" aria-live="polite">Offline — live messages will resume when connected.</div><section class="chatbot-conflict-centre" data-chatbot-conflict-centre aria-label="Offline conflict centre"></section><div class="chatbot-pwa-status" id="chatbot-pwa-update" aria-live="polite">A new version is ready.<button type="button">Update</button></div><div class="chatbot-pwa-device-status" id="chatbot-pwa-device-status" data-online="true" aria-live="polite"><span><span data-pwa-pending>0</span> pending</span><button type="button" data-pwa-sync>Sync now</button></div>
<script>window.TitanChatbotContext=Object.assign(window.TitanChatbotContext||{},{tenant_id:@json(isset($chatbot)?($chatbot->team_id??$chatbot->user_id??null):null),user_id:@json(auth()->id()),device_id:localStorage.getItem('titan-chatbot-device-id')||(()=>{const id=crypto.randomUUID();localStorage.setItem('titan-chatbot-device-id',id);return id;})()});</script>
<script defer src="{{ asset('chatbot-pwa/register.js') }}"></script><script defer src="{{ asset('chatbot-pwa/install.js') }}"></script>
<script defer src="{{ asset('chatbot-pwa/device-db.js') }}"></script><script defer src="{{ asset('chatbot-pwa/generative-ui-state.js') }}"></script><script defer src="{{ asset('chatbot-pwa/crypto-vault.js') }}"></script><script defer src="{{ asset('chatbot-pwa/offline-store.js') }}"></script><script defer src="{{ asset('chatbot-pwa/local-repositories.js') }}"></script><script defer src="{{ asset('chatbot-pwa/local-services.js') }}"></script><script defer src="{{ asset('chatbot-pwa/local-search.js') }}"></script><script defer src="{{ asset('chatbot-pwa/local-ui-bridge.js') }}"></script><script defer src="{{ asset('chatbot-pwa/outbox.js') }}"></script><script defer src="{{ asset('chatbot-pwa/phase1-ui.js') }}"></script>
<script defer src="{{ asset('chatbot-pwa/workcore/contracts.js') }}"></script><script defer src="{{ asset('chatbot-pwa/workcore/database.js') }}"></script><script defer src="{{ asset('chatbot-pwa/workcore/attachments.js') }}"></script><script defer src="{{ asset('chatbot-pwa/workcore/network.js') }}"></script><script defer src="{{ asset('chatbot-pwa/workcore/knowledge.js') }}"></script><script defer src="{{ asset('chatbot-pwa/workcore/offline-packs.js') }}"></script><script defer src="{{ asset('chatbot-pwa/workcore/storage.js') }}"></script><script defer src="{{ asset('chatbot-pwa/workcore/readiness.js') }}"></script><script defer src="{{ asset('chatbot-pwa/workcore/resilience-ui.js') }}"></script><script defer src="{{ asset('chatbot-pwa/workcore/client.js') }}"></script><script defer src="{{ asset('chatbot-pwa/workcore/ui.js') }}"></script><script defer src="{{ asset('chatbot-pwa/frontend-local-first.js') }}"></script><script defer src="{{ asset('chatbot-pwa/workcore/device-capabilities.js') }}"></script><script defer src="{{ asset('chatbot-pwa/workcore/vault.js') }}"></script><script defer src="{{ asset('chatbot-pwa/workcore/hardening.js') }}"></script><script defer src="{{ asset('chatbot-pwa/workcore/self-tests.js') }}"></script><script defer src="{{ asset('chatbot-pwa/workcore/field-workspace.js') }}"></script>
<script defer src="{{ asset('chatbot-pwa/sync/adapter.js') }}"></script><script defer src="{{ asset('chatbot-pwa/sync/engine.js') }}"></script><script defer src="{{ asset('chatbot-pwa/agents/event-bus.js') }}"></script><script defer src="{{ asset('chatbot-pwa/agents/agent-runtime.js') }}"></script><script defer src="{{ asset('chatbot-pwa/agents/device-agents.js') }}"></script><script defer src="{{ asset('chatbot-pwa/agents/index.js') }}"></script><script defer src="{{ asset('vendor/chatbot/js/titan-generative-ui.js') }}"></script><script defer src="{{ asset('chatbot-pwa/byo-execution-bridge.js') }}"></script><script defer src="{{ asset('chatbot-pwa/runtime.js') }}"></script><script defer src="{{ asset('chatbot-pwa/security-integrity.js') }}"></script>
<script>(()=>{const update=document.getElementById('chatbot-pwa-update');if(!update)return;window.addEventListener('chatbot:pwa-update-ready',()=>update.dataset.visible='true');update.querySelector('button')?.addEventListener('click',()=>window.chatbotPwaApplyUpdate?.());})();window.addEventListener('DOMContentLoaded',async()=>{const meta=n=>document.querySelector(`meta[name="${n}"]`)?.content||null;if(window.TitanWorkCore?.client){await window.TitanWorkCore.client.configure({api_base:meta('workcore-api-base')||'',company_id:meta('workcore-company-id')||null,user_id:meta('workcore-user-id')||null,csrf_token:meta('csrf-token')||null});await window.TitanWorkCore.client.refreshPending();}if(window.IndexedDbChatbotSyncAdapter&&window.ChatbotSyncEngine){const adapter=new window.IndexedDbChatbotSyncAdapter();window.chatbotSync=new window.ChatbotSyncEngine(adapter);window.chatbotPwa=window.chatbotPwa||{};window.chatbotPwa.queueSyncOperation=o=>adapter.queue(o);window.chatbotPwa.syncChatbotNow=o=>window.chatbotSync.sync(o);}if(navigator.onLine){window.TitanWorkCore?.client?.sync();window.chatbotSync?.sync().catch(console.warn);}window.addEventListener('online',()=>window.chatbotSync?.sync().catch(console.warn));});</script>
