const fs = require('fs');
const assert = require('assert');
const read = p => fs.readFileSync(p, 'utf8');
const db = read('resources/pwa/chatbot-pwa/device-db.js');
const store = read('resources/pwa/chatbot-pwa/offline-store.js');
const adapter = read('resources/pwa/chatbot-pwa/sync/adapter.js');
const sw = read('resources/pwa/chatbot-sw.js');
assert(db.includes('const DB_VERSION = 5;'));
assert(db.includes('syncRecords'));
assert(db.includes('syncInbox'));
assert(!adapter.includes("indexedDB.open('chatbot-sync-device'"));
assert(adapter.includes("requireDeviceDb().getAll('outbox')") || adapter.includes("db.getAll('outbox')"));
assert(store.includes("'chatbot_id'"));
assert(store.includes("'conversation_uuid'"));
assert(!store.includes("'chatbotId'"));
assert(!store.includes("'conversationId'"));
assert(sw.includes("'titan-chatbot-outbox'"));
assert(sw.includes("TITAN_FLUSH_OUTBOX"));
console.log('Offline Integrity Pass 8: 10 checks passed');
